name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Install OpenSSL
       run: sudo apt-get update && sudo apt-get install -y libssl-dev && sudo apt-get install -y pkg-config


      - name: Set OpenSSL environment variables
        run: |
          echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig" >> $GITHUB_ENV


     - name: Build
       run: cargo build --verbose
